version: '3.1'

volumes:
  mongo_data:

services:
  mongo:
    image: mongo:4-bionic
    volumes:
      - 'mongo_data:/data/db'
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  backend:
    build:
      context: ./taller_oax_backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
  frontend:
    build:
      context: ./taller_oax_frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - backend

