version: '3.1'

volumes:
  mongo_data:

services:
  mongo:
    image: mongo:4-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - 'mongo_data:/data/db'
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
